name: Lint
on: [push]
jobs:
  eslint_check:
    name: Prepare action
    runs-on: ubuntu-latest
    steps:
      # Checkout action must run prior to eslint check
    - name: Checkout 
      uses: actions/checkout@v1
    - name: Lint
      uses: Krizzu/eslint-check-action@v1.1.0
      with:
        ghToken: ${{ secrets.GITHUB_TOKEN }}
        eslintFiles: "lib, scripts"
        eslintConfig: "myConfigs/eslint.config.js"
        eslintExt: "ts, tsx"
